# linear-regression-scratch

Use the "Run" button to execute the code.

In [2]:
!pip install jovian --upgrade --quiet

In [3]:
import jovian

In [4]:
# Execute this to save new versions of the notebook
jovian.commit(project="linear-regression-scratch")

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/noumanamir453/linear-regression-scratch


'https://jovian.ai/noumanamir453/linear-regression-scratch'

In [5]:
import numpy as np
import torch

In [6]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [7]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [8]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.4817,  1.0180, -0.5328],
        [-0.6217,  0.6688,  1.4667]], requires_grad=True)
tensor([-0.0637,  1.5113], requires_grad=True)


In [10]:
def model(x):
    return x @ w.t() + b

In [11]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [12]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 80.3937,  64.0028],
        [ 99.2532,  97.6575],
        [147.3513, 122.1067],
        [ 73.1263,  21.1225],
        [ 93.6041, 125.4857]], grad_fn=<AddBackward0>)


In [13]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(489.4172, grad_fn=<DivBackward0>)


In [14]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[2094.9810, 1667.2301, 1019.0930],
        [-572.3353, -443.1526, -247.4160]])
tensor([22.5457, -5.9250])


In [15]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [16]:
# new weights and biases
print(w)
print(b)

tensor([[ 0.4607,  1.0013, -0.5430],
        [-0.6160,  0.6732,  1.4692]], requires_grad=True)
tensor([-0.0639,  1.5113], requires_grad=True)


In [17]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(409.1872, grad_fn=<DivBackward0>)


In [18]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [19]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(127.2715, grad_fn=<DivBackward0>)


In [20]:
# Predictions
preds

tensor([[ 60.8424,  69.2980],
        [ 75.8345, 103.7808],
        [127.2738, 127.5140],
        [ 41.6267,  30.0515],
        [ 78.8321, 128.9112]], grad_fn=<AddBackward0>)

In [21]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
jovian.commit